name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^2.0.0
  google_fonts: ^5.0.0

  intl: ^0.18.0
  cupertino_icons: ^1.0.6
  flutterfire_cli: ^0.1.1+2
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_database: ^11.1.4
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.3
  image_picker: ^1.1.2
  uuid: ^4.5.1
  flutter_slider_drawer: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

  assets:
    - lib/assets/logo.png  # Periksa apakah logo.png benar-benar ada di folder yang benar

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/logo.png"  # Gunakan gambar logo yang ada
  adaptive_icon_background: "#FFFFFF"
